version: '3.1'

services:
  service-web:
    container_name: $INFRA_WEB_APP
    image: ${INFRA_WEB_IMAGE}:${INFRA_WEB_IMAGE_TAG:-latest}
    build:
      context: ./lawa-react-next
      dockerfile: Dockerfile
      target: production
    restart: always
    hostname: ${INFRA_APP_DOMAIN}
    environment:
      PORT: ${INFRA_WEB_PORT}
      WHOAMI_PORT_NUMBER: ${INFRA_WEB_PORT}
      APP_API_URL: ${INFRA_API_URL}
    ports:
      - ${INFRA_WEB_PORT}:3000
