export const URL_MAIN_PAGE = '/api/main-page'
export const URL_SERVICE_PAGE = '/api/service/top/'
export const URL_SERVICES_PAGE = '/api/service-page'
export const URL_SUB_SERVICES_PAGE = '/api/sub-service/top/'
export const URL_SUB_SERVICES_ITEM_PAGE = '/api/sub-service-item/top/'
export const URL_ABOUT_PAGE = '/api/about/'
export const URL_BLOG_PAGE = '/api/blog/'